### ISSUE TITLE
Got errors on CN FFXIV client

### ISSUE THREAD

**Issue by takaqiao** [Ottermandias/GatherBuddy#26]
`2021-10-20 17:38:19.394 +08:00 [INF] [LOCALPLUGIN] Loading GatherBuddy.dll
2021-10-20 17:38:19.461 +08:00 [ERR] [LOCALPLUGIN] Error while loading GatherBuddy
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GatherBuddy.Utility.FFName.FromPlaceName(UInt32 id) in H:\Projects\FFPlugins\GatherBuddy\Utility\FFName.cs:line 35
   at GatherBuddy.Managers.AetheryteManager..ctor(TerritoryManager territories) in H:\Projects\FFPlugins\GatherBuddy\Managers\AetheryteManager.cs:line 27
   at GatherBuddy.Managers.World..ctor() in H:\Projects\FFPlugins\GatherBuddy\Managers\World.cs:line 142
   at GatherBuddy.Gatherer..ctor(CommandManager commandManager) in H:\Projects\FFPlugins\GatherBuddy\Gatherer.cs:line 39
   at GatherBuddy.GatherBuddy..ctor(DalamudPluginInterface pluginInterface) in H:\Projects\FFPlugins\GatherBuddy\GatherBuddy.cs:line 43
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects)
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in D:\Code\FFXIV\__Dalamud__\Dalamud\Dalamud\Plugin\Internal\LocalPlugin.cs:line 315
2021-10-20 17:38:19.464 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMS0xMC0yMFQxNzozODoxOS40NjQ2MzE4KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uSW5kZXhPdXRPZlJhbmdlRXhjZXB0aW9uOiBJbmRleCB3YXMgb3V0c2lkZSB0aGUgYm91bmRzIG9mIHRoZSBhcnJheS5cclxuICAgYXQgR2F0aGVyQnVkZHkuVXRpbGl0eS5GRk5hbWUuRnJvbVBsYWNlTmFtZShVSW50MzIgaWQpIGluIEg6XFxQcm9qZWN0c1xcRkZQbHVnaW5zXFxHYXRoZXJCdWRkeVxcVXRpbGl0eVxcRkZOYW1lLmNzOmxpbmUgMzVcclxuICAgYXQgR2F0aGVyQnVkZHkuTWFuYWdlcnMuQWV0aGVyeXRlTWFuYWdlci4uY3RvcihUZXJyaXRvcnlNYW5hZ2VyIHRlcnJpdG9yaWVzKSBpbiBIOlxcUHJvamVjdHNcXEZGUGx1Z2luc1xcR2F0aGVyQnVkZHlcXE1hbmFnZXJzXFxBZXRoZXJ5dGVNYW5hZ2VyLmNzOmxpbmUgMjdcclxuICAgYXQgR2F0aGVyQnVkZHkuTWFuYWdlcnMuV29ybGQuLmN0b3IoKSBpbiBIOlxcUHJvamVjdHNcXEZGUGx1Z2luc1xcR2F0aGVyQnVkZHlcXE1hbmFnZXJzXFxXb3JsZC5jczpsaW5lIDE0MlxyXG4gICBhdCBHYXRoZXJCdWRkeS5HYXRoZXJlci4uY3RvcihDb21tYW5kTWFuYWdlciBjb21tYW5kTWFuYWdlcikgaW4gSDpcXFByb2plY3RzXFxGRlBsdWdpbnNcXEdhdGhlckJ1ZGR5XFxHYXRoZXJlci5jczpsaW5lIDM5XHJcbiAgIGF0IEdhdGhlckJ1ZGR5LkdhdGhlckJ1ZGR5Li5jdG9yKERhbGFtdWRQbHVnaW5JbnRlcmZhY2UgcGx1Z2luSW50ZXJmYWNlKSBpbiBIOlxcUHJvamVjdHNcXEZGUGx1Z2luc1xcR2F0aGVyQnVkZHlcXEdhdGhlckJ1ZGR5LmNzOmxpbmUgNDNcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IFN5c3RlbS5SdW50aW1lTWV0aG9kSGFuZGxlLkludm9rZU1ldGhvZChPYmplY3QgdGFyZ2V0LCBPYmplY3RbXSBhcmd1bWVudHMsIFNpZ25hdHVyZSBzaWcsIEJvb2xlYW4gY29uc3RydWN0b3IsIEJvb2xlYW4gd3JhcEV4Y2VwdGlvbnMpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLkNyZWF0ZShUeXBlIG9iamVjdFR5cGUsIE9iamVjdFtdIHNjb3BlZE9iamVjdHMpXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLkxvY2FsUGx1Z2luLkxvYWQoUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gcmVsb2FkaW5nKSBpbiBEOlxcQ29kZVxcRkZYSVZcXF9fRGFsYW11ZF9fXFxEYWxhbXVkXFxEYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxMb2NhbFBsdWdpbi5jczpsaW5lIDMxNSIsIkNvbnRleHQiOiJbTE9DQUxQTFVHSU5dIEVycm9yIHdoaWxlIGxvYWRpbmcgR2F0aGVyQnVkZHlcblN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uSW5kZXhPdXRPZlJhbmdlRXhjZXB0aW9uOiBJbmRleCB3YXMgb3V0c2lkZSB0aGUgYm91bmRzIG9mIHRoZSBhcnJheS5cclxuICAgYXQgR2F0aGVyQnVkZHkuVXRpbGl0eS5GRk5hbWUuRnJvbVBsYWNlTmFtZShVSW50MzIgaWQpIGluIEg6XFxQcm9qZWN0c1xcRkZQbHVnaW5zXFxHYXRoZXJCdWRkeVxcVXRpbGl0eVxcRkZOYW1lLmNzOmxpbmUgMzVcclxuICAgYXQgR2F0aGVyQnVkZHkuTWFuYWdlcnMuQWV0aGVyeXRlTWFuYWdlci4uY3RvcihUZXJyaXRvcnlNYW5hZ2VyIHRlcnJpdG9yaWVzKSBpbiBIOlxcUHJvamVjdHNcXEZGUGx1Z2luc1xcR2F0aGVyQnVkZHlcXE1hbmFnZXJzXFxBZXRoZXJ5dGVNYW5hZ2VyLmNzOmxpbmUgMjdcclxuICAgYXQgR2F0aGVyQnVkZHkuTWFuYWdlcnMuV29ybGQuLmN0b3IoKSBpbiBIOlxcUHJvamVjdHNcXEZGUGx1Z2luc1xcR2F0aGVyQnVkZHlcXE1hbmFnZXJzXFxXb3JsZC5jczpsaW5lIDE0MlxyXG4gICBhdCBHYXRoZXJCdWRkeS5HYXRoZXJlci4uY3RvcihDb21tYW5kTWFuYWdlciBjb21tYW5kTWFuYWdlcikgaW4gSDpcXFByb2plY3RzXFxGRlBsdWdpbnNcXEdhdGhlckJ1ZGR5XFxHYXRoZXJlci5jczpsaW5lIDM5XHJcbiAgIGF0IEdhdGhlckJ1ZGR5LkdhdGhlckJ1ZGR5Li5jdG9yKERhbGFtdWRQbHVnaW5JbnRlcmZhY2UgcGx1Z2luSW50ZXJmYWNlKSBpbiBIOlxcUHJvamVjdHNcXEZGUGx1Z2luc1xcR2F0aGVyQnVkZHlcXEdhdGhlckJ1ZGR5LmNzOmxpbmUgNDNcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IFN5c3RlbS5SdW50aW1lTWV0aG9kSGFuZGxlLkludm9rZU1ldGhvZChPYmplY3QgdGFyZ2V0LCBPYmplY3RbXSBhcmd1bWVudHMsIFNpZ25hdHVyZSBzaWcsIEJvb2xlYW4gY29uc3RydWN0b3IsIEJvb2xlYW4gd3JhcEV4Y2VwdGlvbnMpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLkNyZWF0ZShUeXBlIG9iamVjdFR5cGUsIE9iamVjdFtdIHNjb3BlZE9iamVjdHMpXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLkxvY2FsUGx1Z2luLkxvYWQoUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gcmVsb2FkaW5nKSBpbiBEOlxcQ29kZVxcRkZYSVZcXF9fRGFsYW11ZF9fXFxEYWxhbXVkXFxEYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxMb2NhbFBsdWdpbi5jczpsaW5lIDMxNSJ9
2021-10-20 17:38:19.464 +08:00 [ERR] [PLUGINM] During boot plugin load, an unexpected error occurred`
I looked some code it seems like it doesnt support the CN client language(I dont understand C#tho)

**Comment by Ottermandias** [comment]
Yes, GatherBuddy only supports the four languages from the international client. Since I couldn't even test for CN or KR clients, I have neither the intention nor the option to support them.
