### ISSUE TITLE
The Command "/gather Rarefied Night Pepper" crashes to desktop

### ISSUE THREAD

**Issue by johnysandels** [Ottermandias/GatherBuddy#4]
Issue remains after reinstalling the plugin.

This was at the end of the Dalamud.txt

```
[16:40:39.197][ERR] Exception on OnChatMessage hook.
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at Dalamud.Game.Chat.SeStringHandling.Payload.GetInteger(BinaryReader input, IntegerType type)
   at Dalamud.Game.Chat.SeStringHandling.Payloads.MapLinkPayload.DecodeImpl(BinaryReader reader, Int64 endOfStream)
   at Dalamud.Game.Chat.SeStringHandling.Payload.DecodeChunk(BinaryReader reader)
   at Dalamud.Game.Chat.SeStringHandling.Payload.Decode(BinaryReader reader, DataManager data)
   at Dalamud.Game.Chat.SeStringHandling.SeStringManager.Parse(Byte[] bytes)
   at Dalamud.Game.Internal.Gui.ChatGui.HandlePrintMessageDetour(IntPtr manager, XivChatType chattype, IntPtr pSenderName, IntPtr pMessage, UInt32 senderid, IntPtr parameter)

```

**Comment by Ottermandias** [comment]
I can't reproduce a crash, but obtain a malformed coordinate flag. Can you test if it still occurs if you disable map markers? I'd currently think it's an issue with Chat Coordinates, not Gatherbuddy.

**Comment by johnysandels** [comment]
Yeah doesn't crash with ChatCoordinates disabled. Is it possible to fix the malformed flag? or is it just a weird interaction with chat coords?

**Comment by johnysandels** [comment]
Oh strange, just reinstalled ChatCoordinates and now it works fine.

**Comment by Ottermandias** [comment]
Huh. Well. We fixed it! :D
I think there generally are a few problems with chat coordinates but I also did not want to look at the code for that (otherwise I'd probably have implemented it myself and independent of the plugin). But as long as it doesn't keep crashing, I guess it's fine.

**Comment by johnysandels** [comment]
Just happened again after a relaunch, so I guess this is a persisting issue.

**Comment by johnysandels** [comment]
Yeah can't manage to fix it with any amount of reinstalling and uninstalling. inputting the coordinates for the node with `/coord 26.7 27.5` also crashes the game, so it's definitely chatcoords fault.
