### ISSUE TITLE
[Feature Request] Pinned Fish

### ISSUE THREAD

**Issue by sleepylinde** [Ottermandias/GatherBuddy#67]
Hello,

essentially I absolutely love the new layout and the big changes, especially for gathering on MIN/BTN. However I primarily used the FSH part of the plugin bc being able to see the pinned fish that I need to trigger intution was huge for me. Now I don't understand how I can add for example the Firelight Goldfish, Indigo Prismfish and Green Prismfish without setting an alarm, they have a different fishing window and I need them to be able to get the Warden of the Seven Hues. I only wanna see this in my Fish tab and not in another window like the gather groups or create an alarm, bc I already have enough sensory overload from my HUD as it is. Like I said, I like the big new changes but the function to pin fish was just incredible. Gatherbuddy becomes unusable for me if I have to use the carbuncleplush website to see all fish I have left and their dependancies on one glance. Which becomes a nuisiance with only one screen. 

EDIT: One thing I forgot: Would it be possible to make the fish timer window also expandable more vertical since you can't really see all fish during ocean fishing. 

Hopefully this can be added again. 
Thank you for the hard work.

Best wishes

**Comment by Ottermandias** [comment]
But that's what the GatherWindow is for now? Just add your fish there, then you don't need to keep the big window open at all?
How can you not see all fish during ocean fishing? Can you make a screenshot? The vertical size should scale with catchable fish, so I don't see how this could happen, except if you have moved the window somewhere deep on your screen?

**Comment by sleepylinde** [comment]
I tried to oceanfish before the update (last weekend) and the window wouldnt automatically resize to respond to the amount of fish. I tested it just now and it works!


While trying to set up a new gather group I managed to crash gatherbuddy, here's probably the important bit from my dalamud log.

To reproduce you open a new gather group, add one item to the empty group and then delete the item you added and GB crashes immediadly.
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at GatherBuddy.Gui.Interface.DrawLocationInput(TimedGroup group, Int32 nodeIdx) in H:\Projects\FFPlugins\GatherBuddy\GatherBuddy\Gui\Interface.GatherGroupTab.cs:line 212
   at GatherBuddy.Gui.Interface.DrawGatherGroupNode(TimedGroup group, Int32& idx, Int32 minutes) in H:\Projects\FFPlugins\GatherBuddy\GatherBuddy\Gui\Interface.GatherGroupTab.cs:line 274
   at GatherBuddy.Gui.Interface.DrawGatherGroupNodeTable(TimedGroup group) in H:\Projects\FFPlugins\GatherBuddy\GatherBuddy\Gui\Interface.GatherGroupTab.cs:line 327
   at GatherBuddy.Gui.Interface.DrawGatherGroup(TimedGroup group) in H:\Projects\FFPlugins\GatherBuddy\GatherBuddy\Gui\Interface.GatherGroupTab.cs:line 384
   at ImGuiOtter.ItemDetailsWindow.Draw(String label, Action drawHeader, Action drawDetails) in H:\Projects\FFPlugins\GatherBuddy\ImGuiRaii\ItemSelector.cs:line 471
   at GatherBuddy.Gui.Interface.DrawGatherGroupTab() in H:\Projects\FFPlugins\GatherBuddy\GatherBuddy\Gui\Interface.GatherGroupTab.cs:line 454
   at GatherBuddy.Gui.Interface.Draw() in H:\Projects\FFPlugins\GatherBuddy\GatherBuddy\Gui\Interface.cs:line 49
   at Dalamud.Interface.Windowing.Window.DrawInternal() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 195
   at Dalamud.Interface.Windowing.WindowSystem.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 111
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 305
2022-03-06 17:45:16.878 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wMy0wNlQxNzo0NToxNi44NzU1NDQyKzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5Bcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb246IEluZGV4IHdhcyBvdXQgb2YgcmFuZ2UuIE11c3QgYmUgbm9uLW5lZ2F0aXZlIGFuZCBsZXNzIHRoYW4gdGhlIHNpemUgb2YgdGhlIGNvbGxlY3Rpb24uIChQYXJhbWV0ZXIgJ2luZGV4JylcclxuICAgYXQgR2F0aGVyQnVkZHkuR3VpLkludGVyZmFjZS5EcmF3TG9jYXRpb25JbnB1dChUaW1lZEdyb3VwIGdyb3VwLCBJbnQzMiBub2RlSWR4KSBpbiBIOlxcUHJvamVjdHNcXEZGUGx1Z2luc1xcR2F0aGVyQnVkZHlcXEdhdGhlckJ1ZGR5XFxHdWlcXEludGVyZmFjZS5HYXRoZXJHcm91cFRhYi5jczpsaW5lIDIxMlxyXG4gICBhdCBHYXRoZXJCdWRkeS5HdWkuSW50ZXJmYWNlLkRyYXdHYXRoZXJHcm91cE5vZGUoVGltZWRHcm91cCBncm91cCwgSW50MzImIGlkeCwgSW50MzIgbWludXRlcykgaW4gSDpcXFByb2plY3RzXFxGRlBsdWdpbnNcXEdhdGhlckJ1ZGR5XFxHYXRoZXJCdWRkeVxcR3VpXFxJbnRlcmZhY2UuR2F0aGVyR3JvdXBUYWIuY3M6bGluZSAyNzRcclxuICAgYXQgR2F0aGVyQnVkZHkuR3VpLkludGVyZmFjZS5EcmF3R2F0aGVyR3JvdXBOb2RlVGFibGUoVGltZWRHcm91cCBncm91cCkgaW4gSDpcXFByb2plY3RzXFxGRlBsdWdpbnNcXEdhdGhlckJ1ZGR5XFxHYXRoZXJCdWRkeVxcR3VpXFxJbnRlcmZhY2UuR2F0aGVyR3JvdXBUYWIuY3M6bGluZSAzMjdcclxuICAgYXQgR2F0aGVyQnVkZHkuR3VpLkludGVyZmFjZS5EcmF3R2F0aGVyR3JvdXAoVGltZWRHcm91cCBncm91cCkgaW4gSDpcXFByb2plY3RzXFxGRlBsdWdpbnNcXEdhdGhlckJ1ZGR5XFxHYXRoZXJCdWRkeVxcR3VpXFxJbnRlcmZhY2UuR2F0aGVyR3JvdXBUYWIuY3M6bGluZSAzODRcclxuICAgYXQgSW1HdWlPdHRlci5JdGVtRGV0YWlsc1dpbmRvdy5EcmF3KFN0cmluZyBsYWJlbCwgQWN0aW9uIGRyYXdIZWFkZXIsIEFjdGlvbiBkcmF3RGV0YWlscykgaW4gSDpcXFByb2plY3RzXFxGRlBsdWdpbnNcXEdhdGhlckJ1ZGR5XFxJbUd1aVJhaWlcXEl0ZW1TZWxlY3Rvci5jczpsaW5lIDQ3MVxyXG4gICBhdCBHYXRoZXJCdWRkeS5HdWkuSW50ZXJmYWNlLkRyYXdHYXRoZXJHcm91cFRhYigpIGluIEg6XFxQcm9qZWN0c1xcRkZQbHVnaW5zXFxHYXRoZXJCdWRkeVxcR2F0aGVyQnVkZHlcXEd1aVxcSW50ZXJmYWNlLkdhdGhlckdyb3VwVGFiLmNzOmxpbmUgNDU0XHJcbiAgIGF0IEdhdGhlckJ1ZGR5Lkd1aS5JbnRlcmZhY2UuRHJhdygpIGluIEg6XFxQcm9qZWN0c1xcRkZQbHVnaW5zXFxHYXRoZXJCdWRkeVxcR2F0aGVyQnVkZHlcXEd1aVxcSW50ZXJmYWNlLmNzOmxpbmUgNDlcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuV2luZG93aW5nLldpbmRvdy5EcmF3SW50ZXJuYWwoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXFdpbmRvd2luZ1xcV2luZG93LmNzOmxpbmUgMTk1XHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3dTeXN0ZW0uRHJhdygpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEludGVyZmFjZVxcV2luZG93aW5nXFxXaW5kb3dTeXN0ZW0uY3M6bGluZSAxMTFcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuVWlCdWlsZGVyLk9uRHJhdygpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEludGVyZmFjZVxcVWlCdWlsZGVyLmNzOmxpbmUgMzA1IiwiQ29udGV4dCI6IltcIkdhdGhlckJ1ZGR5XCJdIFVpQnVpbGRlciBPbkJ1aWxkVWkgY2F1Z2h0IGV4Y2VwdGlvbiJ9
2022-03-06 17:45:40.224 +01:00 [INF] [Dalamud.LoadingImage] toLoadingTerri: 341
2022-03-06 17:45:40.224 +01:00 [INF] [Dalamud.LoadingImage] LoadIcon: 122002 detected for r:140 with toLoadingTerri:341
2022-03-06 17:45:40.225 +01:00 [INF] [Dalamud.LoadingImage] Replacing icon for territory 140
2022-03-06 17:45:40.240 +01:00 [INF] [Dalamud.LoadingImage] unitbase: 1FBE3034E10 visible: True
2022-03-06 17:45:40.240 +01:00 [INF] [Dalamud.LoadingImage] unishort: 1FBE30344E0 visible: False
2022-03-06 17:45:57.189 +01:00 [INF] Framework::Destroy!
```

I set up a gather window for my 12 fish I want to keep an eye on, but as I tried to explain before my usecase was just opening the big gatherbuddy window, go to fish tab to check on the pinned fish (I hid already caught fish anyway) and then minimize or close gatherbuddy enterily after checking on the fish. Usually I'd still have the minimized GB or a smaller, resized big window up on my screen to remind myself to check in on the fish periodically. Like so 
![image](https://user-images.githubusercontent.com/73102119/156934349-9fc6ebc5-b3dc-410d-b0c9-695af045f0d1.png)

Now with the gather window there's more steps added to this routine as I need to go to the gather window tab, enable or disable the gathering window since I dont really need to see the fish all the time if none are up, while also minimize or close gatherbuddy after. 

I can absoluletly see the use for this window for a long gathering session for MIN/BTN dont get me wrong but not so much for big fishing, at least for me.

**Comment by Ottermandias** [comment]
You can use `/gbc window` to toggle the window, or you can set up a lot of config for it. Especially for just quickly checking uptimes it should be far better than pinned fish. Just set up a "Only show Gather Window if Holding Key" thing or setup hotkeys? :)
![image](https://user-images.githubusercontent.com/70807659/156934562-5b484670-bd3a-41c0-aea0-215452236c6d.png)

I looked at the crash and I think I found the cause, thanks! :)
